###
@base_URL=http://localhost:5000/api/v1/community
@auth_JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBjcC5pbiIsIm5hbWUiOiJBZG1pbiBVc2VyIiwicGhvbmUiOiIrMTEyMjMzNDQ1NSIsImFkZHJlc3MiOiI3ODkgQWRtaW4gU3QsIEFkbWludmlsbGUsIEluZGlhIiwicGluY29kZSI6IjU0MzIxIiwicGFzc3dvcmQiOiIkMmEkMTAkeFVzTWJyZ2NLSkt3d0ZKOFFvU0lTdUVnMVhTNmZTTHdTUXM5MUtEWWhrZXIubzBaYy5vVXEiLCJpc1N1cGVyQWRtaW4iOmZhbHNlLCJjcmVhdGVkQXQiOiIyMDI1LTAzLTEwVDEwOjIzOjQ0LjM3OVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTAzLTEwVDEwOjIzOjQ0LjM3OVoiLCJwaG90b1VSTCI6Imh0dHBzOi8vcm9ib2hhc2gub3JnL2Rvam8iLCJ1c2VySWQiOm51bGwsInBhcnRuZXJJZCI6bnVsbCwiZXhwZXJ0SWQiOm51bGwsImFkbWluSWQiOjEsImZvbGxvd2VycyI6W10sImZvbGxvd2luZyI6W10sInByaXZhY3lUeXBlIjoiYWxsIiwic2VsZWN0ZWRWaWV3ZXJzIjpbXSwiaXNBY3RpdmUiOnRydWUsInVzZXJUeXBlIjoiYWRtaW4iLCJpYXQiOjE3NTEwNDI4MzMsImV4cCI6MTc1MTEyOTIzM30.KQHedO4LfJx19o2ZI4qejwDevH00fIgdhFMQpfuwPSw

### Get Partner JWT, update the auth_JWT above


GET {{base_URL}}/partner/communities?partnerId=5