###
@base_URL=http://localhost:5000/api/v1/video
@auth_JWT=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbjBAc2VuaW9yLmluIiwibmFtZSI6ImFkbWluMCIsInBob25lIjoiMTIxMjEyIiwiYWRkcmVzcyI6ImFiY2RlZmciLCJwaW5jb2RlIjoiMTIxMjIxIiwicGFzc3dvcmQiOiIkMmEkMTAkMHJwQTB2NFpxRENIZ1VBVE5FQ0NPT202TGxMMjlnMmQ4TGI1OWpHUG50M0U5TVlKeXllQVMiLCJpc1N1cGVyQWRtaW4iOnRydWUsImNyZWF0ZWRBdCI6IjIwMjItMDYtMjRUMTI6MjM6NTkuMjUzWiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMTBUMTE6NTA6NDcuNjMyWiIsInVzZXJUeXBlIjoic3VwZXJhZG1pbiIsImlhdCI6MTY2Njg0NjgyMSwiZXhwIjoxNjY2OTMzMjIxfQ.060HmknY9uqDIMnmwptcEqpYNXUdeIfWvmBXiGVruNE

###
GET {{base_URL}}

###
GET {{base_URL}}/1

###
DELETE {{base_URL}}/4